import { Inter, Ubuntu } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/navbar/Navbar';
import Footer from '@/components/footer/Footer';

const ubuntu = Ubuntu({
	weight: ['300', '400', '500', '700'],
	subsets: ['latin'],
});

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={ubuntu.className}>
				{/* className container works because of "./globals.css". This can be replaced with Tailwind css */}
				<div className='container'>
					<Navbar />
					{children}
					<Footer />
				</div>
				{/* <div className='container'>
					<Navbar />
					{children}
					<Footer />
				</div> */}
			</body>
		</html>
	);
}
